version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
        - "5679:5672"

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5439:5432"

  first_service.api:
    container_name: first_service.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "8001:80"
    image: ${DOCKER_REGISTRY-}first_service_api
    build:
      context: .
      dockerfile: FirstService/Dockerfile
  
  second_service.api:
    container_name: second_service.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ConnectionStrings:SecondServiceContext=Host=postgres;Database=second_service;Username=postgres;Password=root"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8002:80"
    image: ${DOCKER_REGISTRY-}second_service_api
    build:
      context: .
      dockerfile: SecondService/Dockerfile